# @package _global_
defaults:
  - defaults
  - /deep_inv: custom_params_more_iterations
  - /teacher: full_2_teachers
  - /split: full_2_teachers
  - _self_

initial:
  num_batches: 50
  save_path: "/mlodata1/jellouli/experiments/initial_batches/full_2_teacher_custom_params_more.pt"

student:
  adaptive: True
  save_folder: "/mlodata1/jellouli/experiments/student/full_2_teacher_custom_more/adaptive"

amp: True
