# @package _global_
defaults:
  - defaults
  - /deep_inv: custom_params
  - /teacher: full_5_teachers
  - /split: full_5_teachers
  - _self_

initial:
  num_batches: 50
  save_path: "/mlodata1/jellouli/experiments/initial_batches/full_5_teacher_custom_params.pt"

student:
  adaptive: True
  save_folder: "/mlodata1/jellouli/experiments/student/full_5_teacher_custom/adaptive"

amp: True
