# @package _global_
defaults:
  - defaults
  - /deep_inv: custom_params
  - /teacher: full_2_teachers
  - /split: full_2_teachers
  - _self_

teacher:
  num_teachers: 1

initial:
  num_batches: 25
  save_path: "/mlodata1/jellouli/experiments/initial_batches/half_1_teacher_custom_params.pt"

student:
  adaptive: True
  save_folder: "/mlodata1/jellouli/experiments/student/half_1_teacher_custom/adaptive"

amp: True
