train:
  _target_: torchvision.datasets.CIFAR10
  root: "/mlodata1/jellouli"
  train: True
  download: True
    
test:
  _target_: torchvision.datasets.CIFAR10
  root: "/mlodata1/jellouli"
  train: False
  download: True

input_size: [3, 32, 32]