model:
  _target_: fed_distill.resnet.ResNet18

optimizer:
  _partial_: True
  _target_: torch.optim.SGD
  lr: 0.1
  momentum: 0.9
  weight_decay: 5e-4

scheduler: 
  _partial_: True
  _target_: torch.optim.lr_scheduler.MultiStepLR
  milestones: [150, 250]
  gamma: 0.1

criterion:
  _target_: torch.nn.CrossEntropyLoss

batch_size_train: 256
batch_size_test: 2048