defaults:
  - defaults

num_teachers: 5
train_epochs: 300
split_file: "/mlodata1/jellouli/experiments/data_split/full_5_teachers.json"
save_folder: "/mlodata1/jellouli/experiments/teachers/full_5_teachers"

seed: 42